import type { Metadata } from "next";
import {
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar/sidebar";
import { AppSidebar } from "@/components/ui/sidebar/app-sidebar";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/ui/nav";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { setRequestLocale } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as never)) {
    notFound();
  }
  // Enable static rendering
  setRequestLocale(locale);

  return (
    <div>
      <SidebarProvider className="relative flex flex-1">
        <AppSidebar />
        <div className="w-full overflow-hidden">
          <Navbar sidebarTrigger={<SidebarTrigger />} currentLocale={locale} />
          {children}
          <Toaster />
        </div>
      </SidebarProvider>
    </div>
  );
}
